name: CI -ProjectB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_NODE_ENV: test
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      NODE_ENV: test
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "25"

      - run: npm ci
      - run: npx prisma generate
      - run: npm run test
